posts_analysis/config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users

  root :to => 'dashboard#index'

  get 'dashboard/index', as: 'user_root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  post 'post_analysis/run'

  mount ActionCable.server => '/cable'
end

posts_analysis/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

posts_analysis/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:vkontakte]

  # attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :nickname, :provider, :url, :username
  #
  def self.find_for_vkontakte_oauth access_token
    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user
    else
      email = "#{access_token.info.name.gsub(' ', '').downcase + access_token.extra.raw_info.id.to_s}@vk.com"
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte,
                   :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain,
                   :email => email, :password => Devise.friendly_token[0,20], :token => access_token.credentials.token)
    end
  end
end

posts_analysis/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

posts_analysis/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @current_user = User.first
  end
end

posts_analysis/app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

posts_analysis/app/controllers/post_analysis_controller.rb
class PostAnalysisController < ApplicationController
  def run
    current_user = User.first
    PostAnalysisJob.perform(current_user.id, current_user.token, params[:keyword], params[:count].to_i)
  end
end

posts_analysis/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def vkontakte
    @user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

posts_analysis/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :nickname, :provider, :url)
    end
end

posts_analysis/app/helpers/application_helper.rb
module ApplicationHelper
end

posts_analysis/app/helpers/dashboard_helper.rb
module DashboardHelper
end

posts_analysis/app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

posts_analysis/app/helpers/users_helper.rb
module UsersHelper
end

posts_analysis/app/views/dashboard/index.html.haml
= react_component 'DashboardBox', { authenticity_token: form_authenticity_token }

posts_analysis/app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

posts_analysis/app/views/layouts/application.html.haml
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Authproviders"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")
    = action_cable_meta_tag
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li= link_to "#{current_user.username} (#{current_user.provider})", current_user.url
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
    .container
      .content
        .row
          .span9
            = yield
          .span3
            - if !user_signed_in?
              .well.sidebar-nav
                %h3 Providers
              %ul.nav.nav-list
                %li= link_to "Sign in with Vkontakte", user_vkontakte_omniauth_authorize_path

      %footer
        %p © Company 2012
    = javascript_include_tag "application"

posts_analysis/app/views/users/_form.html.haml
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit

posts_analysis/app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

posts_analysis/app/views/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:nickname)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.username, user.url
        %td= user.nickname
        %td= user.provider
        %td= user.sign_in_count
        %td= user.created_at
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

posts_analysis/app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

posts_analysis/app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Username:
  = @user.username
%p
  %strong Nickname:
  = @user.nickname
%p
  %strong Provider:
  = @user.provider
%p
  %strong Url:
  = @user.url
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path